/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProveRoleVerifier__factory } from "./IProveRoleVerifier__factory";
export { IRoleRevealVerifier__factory } from "./IRoleRevealVerifier__factory";
