/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProveRoleVerifier,
  IProveRoleVerifierInterface,
} from "../../interfaces/IProveRoleVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "result",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProveRoleVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IProveRoleVerifierInterface {
    return new utils.Interface(_abi) as IProveRoleVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProveRoleVerifier {
    return new Contract(address, _abi, signerOrProvider) as IProveRoleVerifier;
  }
}
