/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRoleRevealVerifier,
  IRoleRevealVerifierInterface,
} from "../../interfaces/IRoleRevealVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "result",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRoleRevealVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IRoleRevealVerifierInterface {
    return new utils.Interface(_abi) as IRoleRevealVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRoleRevealVerifier {
    return new Contract(address, _abi, signerOrProvider) as IRoleRevealVerifier;
  }
}
