/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proveRoleVerifierSol from "./ProveRoleVerifier.sol";
export * as roleRevealVerifierSol from "./RoleRevealVerifier.sol";
export * as interfaces from "./interfaces";
export { Mafia__factory } from "./Mafia__factory";
