/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProveRoleVerifier } from "./IProveRoleVerifier";
export type { IRoleRevealVerifier } from "./IRoleRevealVerifier";
